### ISSUE TITLE
Open AI call returning as bad request

### ISSUE THREAD

**Issue by jordan-manus** [Team-20-Homies/homepare-backend#16]
trying to make a basic POST to the Open AI API. there is funds in my account, but not sure what the error is in the following response, and how to fix it:

![image](https://github.com/Team-20-Homies/homepare-backend/assets/94319835/fe7991f5-dd99-4865-8091-3e1790df7394)

![image](https://github.com/Team-20-Homies/homepare-backend/assets/94319835/52a6fda5-1176-43c1-95ff-d954ee96543c)

![image](https://github.com/Team-20-Homies/homepare-backend/assets/94319835/e4db1ba8-1450-41de-ae4c-489b1a847df1)

![image](https://github.com/Team-20-Homies/homepare-backend/assets/94319835/ac43456f-9645-42a1-91f3-9d08d8ecde38)

![image](https://github.com/Team-20-Homies/homepare-backend/assets/94319835/818dd331-2040-44ed-b84c-d39f5b6f3212)

**Comment by amygori** [comment]
@jordan-manus Looks like the token is undefined
<img width="582" alt="Screenshot 2024-01-22 at 2 33 12 PM" src="https://github.com/Team-20-Homies/homepare-backend/assets/7226152/738d9e87-6872-408e-b3f2-d0b823d15e77">

**Comment by jordan-manus** [comment]
the api key is held in the .env file and called into the file as apikey. Do you have any suggestions as for why it's not acknowledging it?

**Comment by amygori** [comment]
@jordan-manus As long as you have `dotenv` installed and are using it like `process.env.OPENAI_API_KEY` or whatever the key is in your .env file it should work. You will also need to make sure this env var is set on Render as well, so that it will also be defined in prod.

**Comment by amygori** [comment]
@jordan-manus I thought of one more thing to check -- in your .env file make sure there are no spaces around the `=`

**Comment by jordan-manus** [comment]
closed after removing api token from header and allowing for default, which solved bug
